### ISSUE TITLE
do you have pytorch version of code?

### ISSUE THREAD

**Issue by Hugo101** [cabrust/chia#70]
Hi Clemens,

Thanks for your code of CHIA. I am implementing a hierarchical classification algorithm, and very interest in CHIA. Since I am familiar with Torch, I am wondering whether you implemented a PyTorch version of CHIA or not. It would be great if you could share it if you have. Also, is your tensorflow 1.x or 2.x? 

Thank you so much!

Best,
Changbin

**Comment by cabrust** [comment]
Hi,

unfortunately there is no specific PyTorch implementation. Still, the framework is mostly independent of TF/Keras, so there are only a few places you would have to change to get it working with PyTorch.

Best
Clemens
